Models/Provider.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;

namespace VirtualClinic.Models
{
    public class Provider
    {
        [Key]
        public int ProviderId { get; set; }

        // One to many relationship with User
        public int UserId { get; set; }
        public User User { get; set; }

        // Provider Information
        [MinLength(2, ErrorMessage = "*Needs to be at least 2 characters")]
        [Display(Name = "Specialty", Prompt = "Specialty")]
        public string Specialty { get; set; }
        
        [MinLength(2, ErrorMessage = "*Needs to be at least 2 characters")]
        [Display(Name = "NPI number", Prompt = "NPI number")]
        public string NPInumber { get; set; }

        
        [MinLength(2, ErrorMessage = "*Needs to be at least 2 characters")]
        [Display(Name = "DEA number", Prompt = "DEA number")]
        public string DEAnumber { get; set; }

        public string ExtraField1 { get; set; }
        public string ExtraField2 { get; set; }

        // Provider Bank Information
        [MinLength(2, ErrorMessage = "*Needs to be at least 2 characters")]
        [Display(Name = "Bank Name", Prompt = "Bank Name")]
        public string BankName { get; set; }

        
        [MinLength(2, ErrorMessage = "*Needs to be at least 2 characters")]
        [Display(Name = "Account Number", Prompt = "Account Number")]
        public string AccountNumber { get; set; }

        
        [MinLength(2, ErrorMessage = "*Needs to be at least 2 characters")]
        [Display(Name = "Routing Number", Prompt = "Routing Number")]
        public string RoutingNumber { get; set; }

        [MinLength(2, ErrorMessage = "*Needs to be at least 2 characters")]
        [Display(Name = "Additional Information", Prompt = "Additional Information")]
        public string AdditionalInformation { get; set; }

        public List<Message> Messages { get; set; }

    }

    public class ProviderUpdate
    {

        // Provider Information
        [MinLength(2, ErrorMessage = "*Needs to be at least 2 characters")]
        [Display(Name = "Specialty", Prompt = "Specialty")]
        public string Specialty { get; set; }
        
        [MinLength(2, ErrorMessage = "*Needs to be at least 2 characters")]
        [Display(Name = "NPI number", Prompt = "NPI number")]
        public string NPInumber { get; set; }

        
        [MinLength(2, ErrorMessage = "*Needs to be at least 2 characters")]
        [Display(Name = "DEA number", Prompt = "DEA number")]
        public string DEAnumber { get; set; }

        public string ExtraField1 { get; set; }
        public string ExtraField2 { get; set; }

        // Provider Bank Information
        [MinLength(2, ErrorMessage = "*Needs to be at least 2 characters")]
        [Display(Name = "Bank Name", Prompt = "Bank Name")]
        public string BankName { get; set; }

        
        [MinLength(2, ErrorMessage = "*Needs to be at least 2 characters")]
        [Display(Name = "Account Number", Prompt = "Account Number")]
        public string AccountNumber { get; set; }

        
        [MinLength(2, ErrorMessage = "*Needs to be at least 2 characters")]
        [Display(Name = "Routing Number", Prompt = "Routing Number")]
        public string RoutingNumber { get; set; }

        [MinLength(2, ErrorMessage = "*Needs to be at least 2 characters")]
        [Display(Name = "Additional Information", Prompt = "Additional Information")]
        public string AdditionalInformation { get; set; }

        public string PreferredName { get; set; }

    }
}

// all appointments for a provider foreach appointment load Patient

Controllers/ProviderController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using VirtualClinic.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json.Linq;
using System.IO;

namespace VirtualClinic.Controllers
{
    public class ProviderController : Controller
    {
        private MyContext dbContext;

        public ProviderController(MyContext context)
        {
            dbContext = context;
        }


        // PROVIDER DASHBOARD
        [HttpGet("providerdashboard")]
        public IActionResult ProviderDashboard()
        {
            if (HttpContext.Session.GetInt32("UserId") == null)
            {
                TempData["AuthError"] = "You must be logged in to view this page";
                return RedirectToAction("Index", "Home");
            }

            var userInDb = dbContext.Users.FirstOrDefault(u => u.UserId == HttpContext.Session.GetInt32("UserId"));

            ViewBag.UserLoggedIn = userInDb;



            var providerInfo = dbContext.Providers
                .Include(p => p.User)
                .FirstOrDefault(p => p.UserId == userInDb.UserId);

            // Get all appointments for the logged in provider with all patients
            var providerAppointments = dbContext.Appointments
                .Include(a => a.Patient)
                .ThenInclude(p => p.User)
                .Include(a => a.Provider)
                .ThenInclude(p => p.User)
                .Where(a => a.ProviderId == providerInfo.ProviderId)
                .OrderBy(a => a.DateTime)
                .ToList();

            // ViewBags
            ViewBag.ProviderAppointments = providerAppointments;

            return View();
        }

        // Appointment Attendance Provider View

        [HttpGet("provider/apptattendance/{apptId}")]
        public IActionResult ProviderAttendance(int apptId)
        {
            if (HttpContext.Session.GetInt32("UserId") == null)
            {
                TempData["AuthError"] = "You must be logged in to view this page";
                return RedirectToAction("Index", "Home");
            }

            var userInDb = dbContext.Users.FirstOrDefault(u => u.UserId == HttpContext.Session.GetInt32("UserId"));

            ViewBag.UserLoggedIn = userInDb;

            if (userInDb.userType != "provider")
            {
                TempData["AuthError"] = "You must be logged Provider to view this page";
                return RedirectToAction("Index", "Home");
            }

            // Appointment Info
            var apptInfo = dbContext.Appointments
                .Include(p => p.Patient)
                .ThenInclude(p => p.User)
                .Include(p => p.Provider)
                .ThenInclude(u => u.User)
                .Include(p => p.MedicalNotes)
                .Include(p => p.Medications)    
                .FirstOrDefault(p => p.AppointmentId == apptId);

            // Patient Medications
            ViewBag.PatientInfo = dbContext.Patients
                .Include(p => p.Medications)
                .FirstOrDefault(p => p.UserId == apptInfo.Patient.UserId);

            // Patient Allergies
            ViewBag.PatientAllergies = dbContext.Patients
                .Include(p => p.Allergies)
                .FirstOrDefault(p => p.UserId == apptInfo.Patient.UserId);

            // Patient MedHx
            ViewBag.PatientMedHx = dbContext.Patients
                .Include(p => p.MedicalHistory)
                .FirstOrDefault(p => p.UserId == apptInfo.Patient.UserId);

            // Patient Appointment
            ViewBag.PatientAppt = dbContext.Patients
                .Include(p => p.Appointments)
                .ThenInclude(l => l.Provider)
                .ThenInclude(u => u.User)
                .Include(p => p.Appointments)
                .ThenInclude(m => m.MedicalNotes)
                .FirstOrDefault(p => p.UserId == apptInfo.Patient.UserId);

            // Next appointment (not in the past)
            ViewBag.NextAppointment = dbContext.Appointments
                .Include(p => p.Patient)
                .Include(p => p.Provider)
                .ThenInclude(u => u.User)
                .Where(p => p.PatientId == userInDb.UserId && p.DateTime >= DateTime.Now.AddHours(-1))
                .OrderBy(p => p.DateTime)
                .FirstOrDefault();



            ViewBag.ApptInfo = apptInfo;

            ViewBag.MedicalNote = dbContext.MedicalNotes
                .FirstOrDefault(m => m.PatientId == apptInfo.PatientId
                                     && m.ProviderId == apptInfo.ProviderId
                                     && m.AppointmentId == apptInfo.AppointmentId);


            return View();
        }

        // Post Medical Notes Model
        [HttpPost("add-medical-notes-autosave")]
        public IActionResult AddMedicalNotesAutoSave(MedicalNote newNote)
        {
            // Console.WriteLine("\n###############\n");
            // Console.WriteLine("New Medical Note: ");
            // Console.WriteLine(newNote.PatientId);
            // Console.WriteLine(newNote.AP);
            // // Console.WriteLine(;
            // // Console.WriteLine(HPI);
            // Console.WriteLine("\n###############\n");
            //     // dbContext.MedicalNotes.Add(newMedicalNote);
            //     // dbContext.SaveChanges();

            var newNoteInDb = dbContext.MedicalNotes
                .FirstOrDefault(m => m.PatientId == newNote.PatientId
                                     && m.ProviderId == newNote.ProviderId
                                     && m.AppointmentId == newNote.AppointmentId);
            if (newNoteInDb != null)
            {
                newNoteInDb.HPI = newNote.HPI;
                newNoteInDb.PE = newNote.PE;
                newNoteInDb.Summary = newNote.Summary;
                newNoteInDb.AP = newNote.AP;

                // save changes
                dbContext.SaveChanges();

                var response = "Auto-updated Medical Notes";

                return Json(response);
            }
            else
            {
                dbContext.MedicalNotes.Add(newNote);
                dbContext.SaveChanges();

                var response = "Added new Medical Notes";

                return Json(response);
            }

        }

        // Edit Provider Profile
        [HttpGet("edit/providerprofile")]
        public IActionResult EditProviderProfile()
        {
            // User Logged In
            var userInDb = dbContext.Users.FirstOrDefault(u => u.UserId == HttpContext.Session.GetInt32("UserId"));

            ViewBag.UserLoggedIn = userInDb;

            // Patient Medications
            ViewBag.ProviderInfo = dbContext.Providers
                .Include(p => p.User)
                .FirstOrDefault(p => p.UserId == userInDb.UserId);


            return View();
        }

        // Edit Provider Profile Information
        [HttpPost("edit/providerinfo/")]
        public IActionResult EditPatientInfo(ProviderUpdate UpdatedUser)
        {


            User userInDb = dbContext.Users.FirstOrDefault(u => u.UserId == HttpContext.Session.GetInt32("UserId"));

            // Get the Provider attached to the User
            Provider oldProviderInDb = dbContext.Providers
                .Include(p => p.User)
                .FirstOrDefault(p => p.UserId == userInDb.UserId);

            oldProviderInDb.User.PreferredName = UpdatedUser.PreferredName;
            oldProviderInDb.Specialty = UpdatedUser.Specialty;
            oldProviderInDb.NPInumber = UpdatedUser.NPInumber;
            oldProviderInDb.DEAnumber = UpdatedUser.DEAnumber;
            oldProviderInDb.BankName = UpdatedUser.BankName;
            oldProviderInDb.RoutingNumber = UpdatedUser.RoutingNumber;
            oldProviderInDb.AdditionalInformation = UpdatedUser.AdditionalInformation;

            // CODE SNIPPET ###############################################################
            // string filename = string.Empty;
            // if (fileupload.PostedFile.FileName.Length > 0)
            // {
            //     filename = Path.GetFileName(fileupload.PostedFile.FileName);
            //     if (File.Exists(Server.MapPath("~/Images/" + filename)))
            //     {
            //         Label6.Visible = true;
            //         return;
            //     }
            //     string fileExtension = Path.GetExtension(filename).ToLower();  // this will give you file extension.
            //     string uniqueFileName = Guid.NewGuid().ToString() + fileExtension;   // this will give you unique filename.
            //     fileupload.SaveAs(Server.MapPath("~/Images/" + uniqueFileName)); // save the image with guid name.
            // }
            // com.Parameters.AddWithValue("@Image", (filename.Length > 0) ? "Images/" + uniqueFileName : string.Empty);
            // com.ExecuteNonQuery();

            dbContext.SaveChanges();

            return RedirectToAction("ProviderDashboard");
        }

        // Provider Create Appointment
        // GET METHOD
        [HttpGet("provider/createappointment")]
        public IActionResult ProviderCreateAppt()
        {
            if (HttpContext.Session.GetInt32("UserId") == null)
            {
                TempData["AuthError"] = "You must be logged in to view this page";
                return RedirectToAction("Index", "Home");
            }

            var userInDb = dbContext.Users.FirstOrDefault(u => u.UserId == HttpContext.Session.GetInt32("UserId"));

            Console.WriteLine("User Logged In: ", HttpContext.Session.GetInt32("UserId"));

            ViewBag.UserLoggedIn = userInDb;

            // Patient Medications

            var providerInfo = dbContext.Providers
                .Include(p => p.User)

Views/Provider/ProviderAttendAppt.cshtml
@{
    ViewData["Title"] = "Welcome";
    Layout = "_LayoutBS";
}

@model Appointment


<div class="col-12 col-sm-12 mx-auto">
<div class="col-sm-12 row me-0 mt-3 justify-content-between">
<div class="col-md-12 col-sm-12">
    @* Table with all appointments *@
    <div class="card mb-3">
        <div class="card-header bg-gray-500">
            <h5 class="card-title mb-0">Appoiments With user Waiting:</h5>
        </div>
        <div class="card-body p-0">
            <table id="apptTablePatientWating" class="table table-striped table align-middle mb-0 display" style="width:100%">
                <thead class="bg-light">
                <tr>
                    <th scope="col">Date</th>
                    <th scope="col">Duration</th>
                    <th scope="col">Patient Info</th>
                    <th scope="col" class="text-center">Video Url</th>
                    <th scope="col" class="text-center">Status</th>
                    <th scope="col" class="text-center">Actions</th>
                </tr>
                </thead>
                <tbody>
                @foreach (var appt in ViewBag.ProviderAppointments)
                {
                                @* Check the status and if is for today *@
                    if (appt.Status == "patient_waiting" && appt.DateTime.Date == DateTime.Now.Date)
                    {
                        <tr>
                            <th scope="row">Today @@ @appt.DateTime.ToString("hh:mm tt")</th>
                            <td>@appt.Duration minutes</td>
                            <td><b>@appt.Patient.User.getFullName()</b>, @appt.Patient.User.Sex, @appt.Patient.User.getAgeInYear() y </td>
                            <td class="text-center">
                                <input class="videoUrltoCopy@(appt.AppointmentId)" style="display: none" value="@appt.videoUrl"/>
                                <button class="btn btn-sm btn-light" onclick="autoCopyURL('videoUrltoCopy@(appt.AppointmentId)')" data-bs-placement="right" data-bs-toggle="tooltip" data-bs-html="true" title="Click to Copy<br/>The Video URL<br/>and share">Copy Url <i class="fa-duotone fa-copy"></i></button>
                            </td>
                            @if (appt.getStatus() == "Open")
                            {
                                <td class="text-center">
                                    <span class="badge bg-purple-700 text-light">@appt.getStatus()</span>
                                </td>
                            }
                            else if (appt.getStatus() == "Blocked")
                            {
                                <td class="text-center">
                                    <span class="badge bg-dark text-light">@appt.getStatus()</span>
                                </td>
                            }
                            else if (appt.getStatus() == "Upcoming")
                            {
                                <td class="text-center">
                                    <span class="badge bg-primary text-light">@appt.getStatus()</span>
                                </td>
                            }
                            else if (appt.getStatus() == "Finished")
                            {
                                <td class="text-center">
                                    <span class="badge bg-success text-light">@appt.getStatus()</span>
                                </td>
                            }
                            else if (appt.getStatus() == "In Progress")
                            {
                                <td class="text-center">
                                    <span class="badge bg-warning text-dark">@appt.getStatus()</span>
                                </td>
                            }
                            else
                            {
                                <td class="text-center">
                                    <span class="badge bg-orange-600 text-light">@appt.getStatus()</span>
                                </td>
                            }
                            
                            <td class="text-center">
                                @if (appt.getStatus() == "Open")
                                {
                                    <a class="btn btn-sm btn-danger px-3" asp-action="ProviderDeleteAppt" asp-controller="Provider" asp-route-appointmentId="@appt.AppointmentId" data-bs-placement="left" data-bs-toggle="tooltip" data-bs-html="true" title="Remove">
                                        <i class="fa-solid fa-calendar-circle-minus"></i>
                                    </a>
                                }
                                else if (appt.getStatus() == "Finished")
                                {
                                    <a class="btn btn-sm btn-primary px-3" asp-action="ProviderAttendance" asp-controller="Provider" asp-route-apptId="@appt.AppointmentId" data-bs-placement="left" data-bs-toggle="tooltip" data-bs-html="true" title="See it">
                                        <i class="fa-solid fa-eye"></i>
                                    </a>
                                }
                                else if (appt.getStatus() == "Upcoming" || appt.getStatus() == "In Progress" || appt.Status == "patient_waiting")
                                {
                                    <a class="btn btn-sm btn-success px-3" asp-action="ProviderAttendance" asp-controller="Provider" asp-route-apptId="@appt.AppointmentId" data-bs-placement="left" data-bs-toggle="tooltip" data-bs-html="true" title="Attend">
                                        <i class="fa-solid fa-circle-play"></i>
                                    </a>

                                    @if (@appt.roomIsExpired())
                                    {
                                        <a class="btn btn-sm btn-warning px-3" data-bs-placement="right" data-bs-toggle="tooltip" data-bs-html="true" title="Create Video Room" onclick="createRoom(this,@appt.AppointmentId), reloadPage()">
                                            <i class="fa-duotone fa-camera-web"></i>
                                        </a>
                                    }
                                    else
                                    {
                                        <a class="btn btn-sm btn-secondary px-3" data-bs-placement="right" data-bs-toggle="tooltip" data-bs-html="true" title="Room is created">
                                            <i class="fa-duotone fa-camera-web" disabled></i>
                                        </a>
                                    }
                                }

                            </td>
                        </tr>
                    }
                }
                </tbody>
            </table>
        </div>
    </div>
</div>
    
<hr/>
    
<div class="col-md-12 col-sm-12">
    @* Table with all appointments *@
    <div class="card mb-3">
        <div class="card-header bg-gray-500">
            <h5 class="card-title mb-0">All Appointments for Today:</h5>
        </div>
        <div class="card-body p-0">
            <table id="apptTablePatientToday" class="table table-striped table align-middle mb-0 display" style="width:100%">
                <thead class="bg-light">
                <tr>
                    <th scope="col">Date</th>
                    <th scope="col">Duration</th>
                    <th scope="col">Patient Info</th>
                    <th scope="col" class="text-center">Video Url</th>
                    <th scope="col" class="text-center">Status</th>
                    <th scope="col" class="text-center">Actions</th>
                </tr>
                </thead>
                <tbody>
                @foreach (var appt in ViewBag.ProviderAppointments)
                {
                                    @* Check the status and if is for today *@
                    if ((appt.Status == "patient_waiting" || appt.Status == "taken") && appt.DateTime.Date == DateTime.UtcNow.Date)
                    {
                        <tr>
                            <th scope="row">Today @@ @appt.DateTime.ToString("hh:mm tt")</th>
                            <td>@appt.Duration minutes</td>
                            <td><b>@appt.Patient.User.getFullName()</b>, @appt.Patient.User.Sex, @appt.Patient.User.getAgeInYear() y </td>
                            <td class="text-center">
                                <input class='videoUrltoCopy@(appt.AppointmentId)' style="display: none" value="@appt.videoUrl"/>
                                <button class="btn btn-sm btn-light" onclick="autoCopyURL('videoUrltoCopy@(appt.AppointmentId)')" data-bs-placement="right" data-bs-toggle="tooltip" data-bs-html="true" title="Click to Copy<br/>The Video URL<br/>and share">Copy Url <i class="fa-duotone fa-copy"></i></button>
                            </td>
                            @if (appt.getStatus() == "Open")
                            {
                                <td class="text-center">
                                    <span class="badge bg-purple-700 text-light">@appt.getStatus()</span>
                                </td>
                            }
                            else if (appt.getStatus() == "Blocked")
                            {
                                <td class="text-center">
                                    <span class="badge bg-dark text-light">@appt.getStatus()</span>
                                </td>
                            }
                            else if (appt.getStatus() == "Upcoming")
                            {
                                <td class="text-center">
                                    <span class="badge bg-primary text-light">@appt.getStatus()</span>
                                </td>
                            }
                            else if (appt.getStatus() == "Finished")
                            {
                                <td class="text-center">
                                    <span class="badge bg-success text-light">@appt.getStatus()</span>
                                </td>
                            }
                            else if (appt.getStatus() == "In Progress")
                            {
                                <td class="text-center">
                                    <span class="badge bg-warning text-dark">@appt.getStatus()</span>
                                </td>
                            }
                            else
                            {
                                <td class="text-center">
                                    <span class="badge bg-orange-600 text-light">@appt.getStatus()</span>
                                </td>
                            }
                            <td class="text-center">
                                @if (appt.getStatus() == "Open")
                                {
                                    <a class="btn btn-sm btn-danger px-3" asp-action="ProviderDeleteAppt" asp-controller="Provider" asp-route-appointmentId="@appt.AppointmentId" data-bs-placement="left" data-bs-toggle="tooltip" data-bs-html="true" title="Remove">
                                        <i class="fa-solid fa-calendar-circle-minus"></i>
                                    </a>
                                }
                                else if (appt.getStatus() == "Finished")
                                {
                                    <a class="btn btn-sm btn-primary px-3" asp-action="ProviderAttendance" asp-controller="Provider" asp-route-apptId="@appt.AppointmentId" data-bs-placement="left" data-bs-toggle="tooltip" data-bs-html="true" title="See it">
                                        <i class="fa-solid fa-eye"></i>
                                    </a>
                                }
                                else if (appt.getStatus() == "Upcoming" || appt.getStatus() == "In Progress" || appt.Status == "patient_waiting")
                                {
                                    <a class="btn btn-sm btn-success px-3" asp-action="ProviderAttendance" asp-controller="Provider" asp-route-apptId="@appt.AppointmentId" data-bs-placement="left" data-bs-toggle="tooltip" data-bs-html="true" title="Attend">
                                        <i class="fa-solid fa-circle-play"></i>
                                    </a>
    
                                    @if (@appt.roomIsExpired())
                                    {
                                        <a class="btn btn-sm btn-warning px-3" data-bs-placement="right" data-bs-toggle="tooltip" data-bs-html="true" title="Create Video Room" onclick="createRoom(this,@appt.AppointmentId), reloadPage()">
                                            <i class="fa-duotone fa-camera-web"></i>
                                        </a>
                                    }
                                    else
                                    {
                                        <a class="btn btn-sm btn-secondary px-3" data-bs-placement="right" data-bs-toggle="tooltip" data-bs-html="true" title="Room is created" disabled>
                                            <i class="fa-duotone fa-camera-web"></i>
                                        </a>
                                    }
                                }
    
                            </td>
                        </tr>
                    }
                }
                </tbody>
            </table>
        </div>
    </div>

</div>
</div>
</div>

Views/Provider/_AddMedication.cshtml
@model Medication

@* <form class="row row-cols-lg-auto g-3 align-items-center" asp-action="AddMed" asp-controller="Provider" method="post"> *@
    
<form id="formsubmitnewMedPrescrib" class="mb-3"
      asp-action="AddMed" asp-controller="Provider" method="post"
      >
<div class="col-12">
    
    <input type="hidden" asp-for="ProviderId" value="@ViewBag.ApptInfo.Provider.ProviderId"/>
    <input type="hidden" asp-for="PatientId" value="@ViewBag.ApptInfo.Patient.PatientId"/>
    <input type="hidden" asp-for="AppointmentId" value="@ViewBag.ApptInfo.AppointmentId"/>
    <div class="row flex-row">
        <div class="col-6">
            <div class="col-12">
                <label class="visually-hidden" for="inlineFormInputGroupUsername">Medication Name</label>
                <div class="input-group mb-3">
                    <div class="input-group-text"><i class="fa-solid fa-pills"></i></div>
                    <input type="text" class="form-control" id="inlineFormInputGroupUsername" placeholder="Medication Name"
                           asp-for="Name" required>
                </div>
            </div>
            <div class="col-12">
                <label class="visually-hidden" for="inlineFormSelectPref">Description</label>
                <div class="input-group mb-3">
                    <div class="input-group-text"><i class="fa-solid fa-pen-field"></i></div>
                    <input type="text" class="form-control" id="inlineFormInputGroupUsername" placeholder="Take # Pills x Days"
                           asp-for="Description" required>
                </div>
            </div>
            <div class="col-12">
                <button id="addmedicationbtn" type="submit" class="btn btn-primary w-100" data-bs-display="static" disabled>Add Medication</button>
            </div>
        </div>
        <div class="col-6">
            <div class="col-12">
                <ul class="list-group" id="listOfMedPrescribed">

                    <partial name="_PrescribedMed"/>


                </ul>
            </div>
        </div>
    </div>

</div>
</form>

Views/Provider/_CreateAppt.cshtml
@model Appointment


<div class="col-md-12 col-sm-12 mb-4">
    <h4>
        <i class="fa fa-calendar-check-o" aria-hidden="true"></i>
        <span>Appointments</span>
    </h4>
    <hr/>
    <form asp-action="ProviderCreateApptPost" asp-controller="Provider" method="post">

        <input type="hidden" asp-for="PatientId" value="1">
        <input type="hidden" asp-for="ProviderId" value="@ViewBag.ProviderInfo.ProviderId">
        <input type="hidden" asp-for="Status" value="created">

        <div class="input-group mb-3">
            <label asp-for="DateTime" class="input-group-text"></label>
            <input asp-for="DateTime" class="form-control" value="@DateTime.Now.ToString("yyyy-MM-ddThh:00")">
            <label asp-for="Duration" class="input-group-text"></label>
            <select asp-for="Duration" class="form-select">
                <option value="15">15 min</option>
                <option value="20">20 min</option>
                <option value="30" selected>30 min</option>
                <option value="60">60 min</option>
            </select>
            <button class="btn btn-primary" type="submit" id="button-addon2">Create <i class="fa-solid fa-calendar-plus"></i></button>
        </div>
    </form>
</div>